title: 2+2=4
email: doktordroid@protonmail.com
description: >
  "A szabadság az, ha szabadságunkban áll kimondani, hogy <i>kettő meg kettő az négy</i>.
   Ha ezt megtehetjük, minden egyéb magától következik." - George Orwell, 1984
baseurl: ""
url: "https://2m2a4.github.io"
author: Doktor Droid
github_username: doktordroid
exclude: [bin]

defaults:
  - scope:
      path: "_campaigns"
    values:
      layout: campaign
      display: A
  - scope:
      path: "_variations"
    values:
      layout: variation

collections:
  campaigns:
    output: true
  variations:
    output: true
  prepared:
    output: false
  programok:
    output: true

# Build settings
markdown: kramdown
# theme: minima
gems:
  - jekyll-feed
